# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/code/Lox

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/code/Lox

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/code/Lox/CMakeFiles /home/code/Lox/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/code/Lox/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named li_test

# Build rule for target.
li_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 li_test
.PHONY : li_test

# fast build rule for target.
li_test/fast:
	$(MAKE) -f CMakeFiles/li_test.dir/build.make CMakeFiles/li_test.dir/build
.PHONY : li_test/fast

#=============================================================================
# Target rules for targets named LI

# Build rule for target.
LI: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LI
.PHONY : LI

# fast build rule for target.
LI/fast:
	$(MAKE) -f CMakeFiles/LI.dir/build.make CMakeFiles/LI.dir/build
.PHONY : LI/fast

src/Lox.o: src/Lox.cc.o

.PHONY : src/Lox.o

# target to build an object file
src/Lox.cc.o:
	$(MAKE) -f CMakeFiles/LI.dir/build.make CMakeFiles/LI.dir/src/Lox.cc.o
.PHONY : src/Lox.cc.o

src/Lox.i: src/Lox.cc.i

.PHONY : src/Lox.i

# target to preprocess a source file
src/Lox.cc.i:
	$(MAKE) -f CMakeFiles/LI.dir/build.make CMakeFiles/LI.dir/src/Lox.cc.i
.PHONY : src/Lox.cc.i

src/Lox.s: src/Lox.cc.s

.PHONY : src/Lox.s

# target to generate assembly for a file
src/Lox.cc.s:
	$(MAKE) -f CMakeFiles/LI.dir/build.make CMakeFiles/LI.dir/src/Lox.cc.s
.PHONY : src/Lox.cc.s

src/Scanner.o: src/Scanner.cc.o

.PHONY : src/Scanner.o

# target to build an object file
src/Scanner.cc.o:
	$(MAKE) -f CMakeFiles/LI.dir/build.make CMakeFiles/LI.dir/src/Scanner.cc.o
.PHONY : src/Scanner.cc.o

src/Scanner.i: src/Scanner.cc.i

.PHONY : src/Scanner.i

# target to preprocess a source file
src/Scanner.cc.i:
	$(MAKE) -f CMakeFiles/LI.dir/build.make CMakeFiles/LI.dir/src/Scanner.cc.i
.PHONY : src/Scanner.cc.i

src/Scanner.s: src/Scanner.cc.s

.PHONY : src/Scanner.s

# target to generate assembly for a file
src/Scanner.cc.s:
	$(MAKE) -f CMakeFiles/LI.dir/build.make CMakeFiles/LI.dir/src/Scanner.cc.s
.PHONY : src/Scanner.cc.s

src/Token.o: src/Token.cc.o

.PHONY : src/Token.o

# target to build an object file
src/Token.cc.o:
	$(MAKE) -f CMakeFiles/LI.dir/build.make CMakeFiles/LI.dir/src/Token.cc.o
.PHONY : src/Token.cc.o

src/Token.i: src/Token.cc.i

.PHONY : src/Token.i

# target to preprocess a source file
src/Token.cc.i:
	$(MAKE) -f CMakeFiles/LI.dir/build.make CMakeFiles/LI.dir/src/Token.cc.i
.PHONY : src/Token.cc.i

src/Token.s: src/Token.cc.s

.PHONY : src/Token.s

# target to generate assembly for a file
src/Token.cc.s:
	$(MAKE) -f CMakeFiles/LI.dir/build.make CMakeFiles/LI.dir/src/Token.cc.s
.PHONY : src/Token.cc.s

test/main.o: test/main.cc.o

.PHONY : test/main.o

# target to build an object file
test/main.cc.o:
	$(MAKE) -f CMakeFiles/li_test.dir/build.make CMakeFiles/li_test.dir/test/main.cc.o
.PHONY : test/main.cc.o

test/main.i: test/main.cc.i

.PHONY : test/main.i

# target to preprocess a source file
test/main.cc.i:
	$(MAKE) -f CMakeFiles/li_test.dir/build.make CMakeFiles/li_test.dir/test/main.cc.i
.PHONY : test/main.cc.i

test/main.s: test/main.cc.s

.PHONY : test/main.s

# target to generate assembly for a file
test/main.cc.s:
	$(MAKE) -f CMakeFiles/li_test.dir/build.make CMakeFiles/li_test.dir/test/main.cc.s
.PHONY : test/main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... li_test"
	@echo "... LI"
	@echo "... src/Lox.o"
	@echo "... src/Lox.i"
	@echo "... src/Lox.s"
	@echo "... src/Scanner.o"
	@echo "... src/Scanner.i"
	@echo "... src/Scanner.s"
	@echo "... src/Token.o"
	@echo "... src/Token.i"
	@echo "... src/Token.s"
	@echo "... test/main.o"
	@echo "... test/main.i"
	@echo "... test/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

